### ISSUE TITLE
Have a volunteering type dropdown for the volunteering application form

### ISSUE THREAD

**Issue by hantuzun** [panvol/pandemic-volunteers#11]
Upon consulting to https://journify.co/ founder Lamia and https://usepanda.com/ founder Ahmet and designer Siemon fro COVID accelerator, we should have a dropdown for volunteering type. We will need it organisational purposes in the future anyways. But it will convey legitimacy now as well.

We could have an enum column named `team` or `role`. Any better descriptions are welcome.

It should be the first item in the list. The dropdown should list the roles in the order they are presented at the page. There should be an "Other" option at the bottom. We should write not selected and "Other" options as `nil` to the DB.

**Comment by Donnadieu** [comment]
@hantuzun what "type" of volunteers are we thinking ?

**Comment by hantuzun** [comment]
7 options:
The 5 types listed on the page now + "Operations Team" + "Other"

I'm going to try to name the teams now

**Comment by Donnadieu** [comment]
@hantuzun so we are calling them `teams`? Something like:

```
class Volunteer < ApplicationRecord
  enum team: ["Help nurses in hospitals", ...]
  validates :email, presence: true, format: /\b[A-Z0-9._%a-z\-]+@(?:[A-Z0-9a-z\-]+\.)+[A-Za-z]{2,4}\z/
  validates :phone, presence: true, format: /\A\+?[\d\(\)\-\ ]{7,}\z/
  validates :name, :about, presence: true
  validates :email, uniqueness: true
end
```

**Comment by hantuzun** [comment]
Well yes, something along those lines. We should have the enum in the DB as well.

**Comment by hantuzun** [comment]
We are planning to have the following groups:
 * "Hospital Support" (Help nurses in hospitals)
 * "Triage Support" (Triage for patients at home: Telephone triage support & Mobile triage support)
 * "Healthcare Support" (Give care to dependents of healthcare workers)
 * "Elderly Support" (Cater to the needs of the elderly & those in need)
 * "Operations Support" (Helping the platform, coordinating the efforts of field staff)
 * "Research Communication" (Curate academic research for busy doctors: Researchers & ambassadors. Details: https://www.notion.so/Research-Communications-Team-4e02f9996dbf42dbb06b579a005b25d2) What about "Research Support"?

How do these names sound? 

Then there is a question of how to call these groups. Because "Hospital Support Group", for instance, is misleading.

Some options (Research Communication's naming is more difficult):

* "Hospital Teams"
* "Triage Teams"
* "Healthcare Teams"
* "Elderly Teams"
* "Operations Teams"
* "Research Teams"

---

* "Hospital Support Teams"
* "Triage Support Teams"
* "Healthcare Support Teams"
* "Elderly Support Teams"
* "Operations Support Teams"
* "Research Support Teams"

------------------------------

* "Hospital Units"
* "Triage Units"
* "Healthcare Units"
* "Elderly Units"
* "Operations Units"
* "Research Units"

---

* "Hospital Support Units"
* "Triage Support Units"
* "Healthcare Support Units"
* "Elderly Support Units"
* "Operations Support Units"
* "Research Support Units"

------------------------------

* "Hospital Crews"
* "Triage Crews"
* "Healthcare Crews"
* "Elderly Crews"
* "Operations Crews"
* "Research Crews"

---

* "Hospital Support Crews"
* "Triage Support Crews"
* "Healthcare Support Crews"
* "Elderly Support Crews"
* "Operations Support Crews"
* "Research Support Crews"

------------------------------

* "Hospital Squads"
* "Triage Squads"
* "Healthcare Squads"
* "Elderly Squads"
* "Operations Squads"
* "Research Squads"

---

* "Hospital Support Squads"
* "Triage Support Squads"
* "Healthcare Support Squads"
* "Elderly Support Squads"
* "Operations Support Squads"
* "Research Support Squads"

------------------------------

How should we name them?

**Comment by Donnadieu** [comment]
I like this names:

```
"Hospital Support Units"
"Triage Support Units"
"Healthcare Support Units"
"Elderly Support Units"
"Operations Support Units"
"Research Support Units"
```
They're specific enough. When calling the db column out of an instance of a volunteer could be something like `volunteer.support_unit #=> "Hospital"`

**Comment by hantuzun** [comment]
I like "Units" too. Let's get a few more opinions too.

**Comment by hantuzun** [comment]
Enums should be lowercase. I like this guide: https://sipsandbits.com/2018/04/30/using-database-native-enums-with-rails/

```
class Post < ApplicationRecord
  enum status: {
    draft: "draft",
    reviewed: "reviewed",
    published: "published"
  }
end
```

**Comment by Donnadieu** [comment]
> Enums should be lowercase. I like this guide: https://sipsandbits.com/2018/04/30/using-database-native-enums-with-rails/
> 
> ```
> class Post < ApplicationRecord
>   enum status: {
>     draft: "draft",
>     reviewed: "reviewed",
>     published: "published"
>   }
> end
> ```

Thinking about using integers for keys

**Comment by Donnadieu** [comment]
> I like "Units" too. Let's get a few more opinions too.

I'd like to be specific I don't know what you think about `support_unit`. 

```
class Volunteer < ApplicationRecord
  enum support_unit {
    "Hospital" => 0,
    "Triage" => 1,
    "Healthcare" => 2,
    "Elderly" => 3,
    "Operations" => 4,
    "Research" => 5,
  }
  validates :email, presence: true, format: /\b[A-Z0-9._%a-z\-]+@(?:[A-Z0-9a-z\-]+\.)+[A-Za-z]{2,4}\z/
  validates :phone, presence: true, format: /\A\+?[\d\(\)\-\ ]{7,}\z/
  validates :name, :about, presence: true
  validates :email, uniqueness: true
end
```

**Comment by hantuzun** [comment]
I'm fine with `support_unit`.

**Comment by hantuzun** [comment]
But could you have a look at the title "Integer columns are hard to understand without actual context" of https://sipsandbits.com/2018/04/30/using-database-native-enums-with-rails/ ?

Also @kopchickm and @ScottDuane might have something to say about this issue.

**Comment by Donnadieu** [comment]
Ok I'll wait for their feedback

**Comment by hantuzun** [comment]
No need to :)

Are you okay with the following as recommended in the article? 

```rb
class Volunteer < ApplicationRecord
  enum group: {
    hospital: "hospital",
    triage: "triage",
    healthcare: "healthcare",
    elderly: "elderly",
    research: "research",
    operations: "operations",
    other: "other"
  }
  ...
end
```
A mentor recommends using:
* "Hospital Groups"
* "Triage Groups"
* "Healthcare Groups"
* "Elderly Groups"
* "Operations Groups"
* "Research Groups"

What do you think?

**Comment by Donnadieu** [comment]
@hantuzun that could also work. Want to with Groups instead?

**Comment by Donnadieu** [comment]
> No need to :)
> 
> Are you okay with the following as recommended in the article?
> 
> ```ruby
> class Volunteer < ApplicationRecord
>   enum group: {
>     hospital: "hospital",
>     triage: "triage",
>     healthcare: "healthcare",
>     elderly: "elderly",
>     research: "research",
>     operations: "operations",
>     other: "other"
>   }
>   ...
> end
> ```
> 
> A mentor recommends using:
> 
> * "Hospital Groups"
> * "Triage Groups"
> * "Healthcare Groups"
> * "Elderly Groups"
> * "Operations Groups"
> * "Research Groups"
> 
> What do you think?

**Comment by hantuzun** [comment]
She changed her mind :D

What do you think about "Crews"?

* "Hospital Crews"
* "Triage Crews"
* "Healthcare Crews"
* "Elderly Crews"
* "Operations Crews"
* "Research Crews"

**Comment by Donnadieu** [comment]
Oooh I don't know about that one. Crew is a terminology used in hospitals as well as staff. And we need to make the distinction between a "volunteer" and a staff member

**Comment by hantuzun** [comment]
> "Crew is a terminology used in hospitals as well as staff. And we need to make the distinction between a "volunteer" and a staff member"

Yes... But wouldn't they be just called "volunteers" at the hospital?
