### ISSUE TITLE
Send registration emails

### ISSUE THREAD

**Issue by hantuzun** [panvol/pandemic-volunteers#13]
Upon receiving form submissions, we should send registration emails.

I've experience with https://sendgrid.com/

**Comment by Donnadieu** [comment]
@hantuzun Why not use the built in rails mailer?

**Comment by hantuzun** [comment]
Yes, we use that to integrate with SendGrid: https://sendgrid.com/docs/for-developers/sending-email/rubyonrails/

Rails doesn't run a mail server AFAIK, right?

**Comment by Donnadieu** [comment]
@hantuzun got you. I'll take a look at this after volunteers
