### ISSUE TITLE
Remove regex validation for phone numbers

### ISSUE THREAD

**Issue by hantuzun** [panvol/pandemic-volunteers#23]
On @ `spec/factories/volunteer_factory.rb:`

```rb
    phone { Faker::PhoneNumber.phone_number }
```

**Comment by hantuzun** [comment]
We should require phone numbers. If an applicant is not giving their phone number they are probably not going to bother to volunteer neither.

**Comment by hantuzun** [comment]
Could we make sure there's at least 4 digits?

https://stackoverflow.com/a/43993566

What do you think?

**Comment by ewynx** [comment]
Sounds good to me. I implement that?

**Comment by hantuzun** [comment]
Relaxed the requirement in the following PR instead: https://github.com/panvol/pandemic-volunteers/pull/39

Handles all of the formats here and more: https://github.com/faker-ruby/faker/blob/master/doc/default/phone_number.md#phone_number
